-- Up Migration
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS city TEXT,
  ADD COLUMN IF NOT EXISTS state TEXT,
  ADD COLUMN IF NOT EXISTS zip_code VARCHAR(20),
  ADD COLUMN IF NOT EXISTS avatar_url TEXT,
  ADD COLUMN IF NOT EXISTS relationship VARCHAR(20);

-- Down Migration
ALTER TABLE users
  DROP COLUMN IF EXISTS relationship,
  DROP COLUMN IF EXISTS avatar_url,
  DROP COLUMN IF EXISTS zip_code,
  DROP COLUMN IF EXISTS state,
  DROP COLUMN IF EXISTS city;
